# Generated by Django 5.2.1 on 2025-07-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_ghlauthcredentials_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ghlauthcredentials",
            name="scope",
            field=models.TextField(blank=True, null=True),
        ),
    ]
