# Generated by Django 5.2.1 on 2025-05-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ghl_id',
            new_name='contact_id',
        ),
    ]
