# Generated by Django 5.2.1 on 2025-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0002_rename_ghl_id_contact_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
