# Generated by Django 5.2.1 on 2025-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0002_alter_questionoption_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean/Yes-No'), ('choice', 'Multiple Choice'), ('multiple_choice', 'Multiple Selection'), ('date', 'Date'), ('email', 'Email'), ('extra_choice', 'Extra Choice')], max_length=20),
        ),
    ]
