# Generated by Django 5.2.1 on 2025-06-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedservice',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_plans', to='data_management_app.purchase'),
        ),
        migrations.AlterField(
            model_name='purchasedservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management_app.service'),
        ),
    ]
