# Generated by Django 5.2.1 on 2025-05-26 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0003_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_price', models.DecimalField(decimal_places=2, help_text='Minimum price for this service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean/Yes-No'), ('choice', 'Multiple Choice'), ('multiple_choice', 'Multiple Selection'), ('date', 'Date'), ('email', 'Email')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional price per unit for this question', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='data_management_app.service')),
            ],
            options={
                'ordering': ['service', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pricing_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Base price before discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='data_management_app.service')),
            ],
            options={
                'ordering': ['service', 'name'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='data_management_app.service')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PricingOptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='data_management_app.feature')),
                ('pricing_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_features', to='data_management_app.pricingoption')),
            ],
            options={
                'verbose_name': 'Pricing Option Feature',
                'verbose_name_plural': 'Pricing Option Features',
                'unique_together': {('pricing_option', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for selecting this option', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='data_management_app.question')),
            ],
            options={
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'value')},
            },
        ),
    ]
