# Generated by Django 5.2.1 on 2025-05-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0004_service_question_pricingoption_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='data_management_app.contact')),
                ('price_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='data_management_app.pricingoption')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='data_management_app.service')),
            ],
        ),
    ]
