# Generated by Django 5.2.1 on 2025-06-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0004_alter_purchasedservice_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedservice',
            name='purchase',
            field=models.ForeignKey(default=104, on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='data_management_app.purchase'),
            preserve_default=False,
        ),
    ]
