# Generated by Django 5.2.1 on 2025-06-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0005_alter_purchasedservice_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedservice',
            name='selected_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_service', to='data_management_app.purchasedserviceplan'),
        ),
        migrations.AlterField(
            model_name='purchasedserviceplan',
            name='purchased_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_feature_plans', to='data_management_app.purchasedservice'),
        ),
    ]
