# Generated by Django 5.2.1 on 2025-06-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0006_alter_purchasedservice_selected_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedservice',
            name='price_plan',
        ),
        migrations.RemoveField(
            model_name='purchasedservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='questionoptionanswers',
            name='question_option',
        ),
        migrations.RemoveField(
            model_name='questionsandanswers',
            name='question',
        ),
    ]
