# Generated by Django 5.2.1 on 2025-06-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0009_customproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedserviceplan',
            name='purchased_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_feature_plans', to='data_management_app.purchasedservice'),
        ),
    ]
