# Generated by Django 5.2.1 on 2025-07-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_management_app", "0010_alter_purchasedserviceplan_purchased_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_id", models.CharField(max_length=500)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Home, Office, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this location for the contact"
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("gate_code", models.CharField(blank=True, max_length=20, null=True)),
                ("number_of_floors", models.PositiveIntegerField()),
                ("property_sqft", models.PositiveIntegerField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_location",
                        to="data_management_app.contact",
                    ),
                ),
            ],
        ),
    ]
