# Generated by Django 5.2.1 on 2025-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_management_app", "0011_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="number_of_floors",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="property_sqft",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[("residential", "Residential"), ("commercial", "Commercial")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
