# Generated by Django 5.2.1 on 2025-07-02 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_management_app",
            "0012_alter_address_city_alter_address_number_of_floors_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_address",
                to="data_management_app.address",
            ),
        ),
    ]
